name: chrome_gen
version: 0.0.4
authors:
- Devon Carew <devoncarew@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: An *experimental* library for accessing the Chrome APIs in a packaged app or extension.
homepage: https://github.com/dart-gde/chrome_gen.dart
environment:
  sdk: '>=0.7.6+4'
dependencies:
  logging: '>=0.7.6+4'
dev_dependencies:
  args: '>=0.7.6+4'
  browser: '>=0.7.6+4'
  parsers: any
  unittest: '>=0.7.6+4'
