name: chrome_gen
version: 0.0.3
homepage: https://github.com/dart-gde/chrome_gen.dart
authors:
- Devon Carew <devoncarew@gmail.com>
- Adam Singer <financeCoding@gmail.com>
description: An *experimental* library for accessing the Chrome APIs in a packaged app or extension.
dependencies:
  logging: any
dev_dependencies:
  args: any
  browser: any
  parsers: any
  unittest: any
